### ISSUE TITLE
Computer not receiving any inputs from the Pi

### ISSUE THREAD

**Issue by DaSu15** [josephillips85/gamepademu#1] opened 2019-09-03 18:33 UTC
After installing the drivers the IOS guitar connects to the Pi without any issues, but pressing buttons on the controller doesn't send any inputs to the PC

**Comment by josephillips85** [comment] 2019-09-03 18:45
Hi Dasu15
im sorry for hear that plese send me more information like 
What operating system are you using . 
What raspberry pi are you using.?
are you using a Correct data cable (trust me i had a lot of issues with some "Charger cables" that only work for charging devices and not pass data)
are you using the correct port on the PI

Did you see the gamepad on your devices?

thanks

**Comment by josephillips85** [comment] 2019-09-03 20:02
Also i forgot try to not use USB Hubs sometimes they are a little bit problematic @DaSu15

**Comment by DaSu15** [comment] 2019-09-03 20:39
Windows 10
Pi Zero W
I used a cable that came with a phone. I assume it's a data cable?
I did use the correct port and my PC identified the controller but no inputs were shown.

**Comment by IMS212** [comment] 2019-09-03 20:39
Also sorry for hijacking the thread, but why would this not work on an rpi3 or the PC itself, emulating a usb device? @josephillips85

**Comment by DaSu15** [comment] 2019-09-03 20:56
Also do you possibly have any idea about the poll rate of the controller when it's connected this way? And if it isn't any different to normal controllers is there any possibility of somehow improving that?

As far as I know the poll rate of normal GHL controllers is 125hz and I assume that it's limited by the drivers and that's why I'm wondering if it could possibly be higher this way.

**Comment by josephillips85** [comment] 2019-09-03 21:41
@DaSu15  
please try the input on this 

https://html5gamepad.com/

**Comment by josephillips85** [comment] 2019-09-03 21:44
@IMS212 Well the problem with Raspberry pi 3 is because the USB ports are connected  thought . a USB HUB so is not possible emulate a USB device as i know

I guess Raspberry pi 4 is possible to do that. i need to buy one .

**Comment by IMS212** [comment] 2019-09-03 21:44
I see, but would it be possible to run this on a pc itself and emulate the usb?

**Comment by josephillips85** [comment] 2019-09-03 21:45
@IMS212 use a computer for emulate a USB device?

**Comment by josephillips85** [comment] 2019-09-03 21:45
@IMS212  i guess but i guess need some modifications.

**Comment by DaSu15** [comment] 2019-09-03 22:05
@josephillips85 I did try the input on that website and it didn't show the controller at all, but I'm assuming that's because the controller isn't sending any inputs. I was able to check the input through windows though and didn't show any inputs there either.

**Comment by josephillips85** [comment] 2019-09-03 22:15
@DaSu15  i can replicate the issue now let me investigate whats going on.

**Comment by josephillips85** [comment] 2019-09-03 22:29
@DaSu15  looks like . a Windows issue 
At least i can replicate the issue on virtualbox but is not very acurrate let me find a windows Computer to trobleshoot this issue.

on Mac is working fine.

**Comment by josephillips85** [comment] 2019-09-03 22:31
@DaSu15 just for test please try to change on another usb ports.

**Comment by DaSu15** [comment] 2019-09-03 22:35
@josephillips85 I tried different usb ports and I tried different computers but the same issue still occurred.

**Comment by josephillips85** [comment] 2019-09-03 22:42
@DaSu15 all windows right?
just to make sure do another thing log via ssh
as sudo run
pip uninstall pygatt
reset the device unplugging the cable and try again.

**Comment by DaSu15** [comment] 2019-09-03 22:58
@josephillips85 All windows yes.
And I did what you said and I can't see any difference from before.

**Comment by DaSu15** [comment] 2019-09-03 23:04
One thing I noticed. When i turn on the Pi I get an error message from Windows that says that it can't recognize the usb device. Then some time after it appears as IOS Guitar Hero Live guitar in the control panel.
Also for some reason it shows up as IOS Guitar Hero Live guitar on my laptop, but not on my PC.

**Comment by DaSu15** [comment] 2019-09-11 10:18
Any progress so far? Is there any hope?

**Comment by josephillips85** [comment] 2019-09-11 16:00
Hi
Well I’m still looking on Windows vm but I’m discover the issue still
happens with a steel series game pad too

So I need to boot camp windows to troubleshoot this

**Comment by clouser123** [comment] 2019-09-15 19:06
Same issue as described above. 

Device: Raspberry Pi Zero W
Host device: Laptop, Windows 10
Controller: GHL iOS 6 buttons (2 controllers brand new, out of the box)

No USB hub. 

Windows shows that the device was not recognized, but at that point I can connect the guitar to the Pi. 

The guitar appears in devices (including in JoyToKey) but no input is taken. It appears as if the driver should be installing though. See the attached screenshot.


![image](https://user-images.githubusercontent.com/47701369/64926353-feee2700-d804-11e9-8d4f-ffce67f8bf72.png)

**Comment by josephillips85** [comment] 2019-09-15 19:59
Probably I will need write a windows driver

Or try to clone a generic gamepad instead the weird part is how Mac
recognize the gamepad as a generic and work great on it

**Comment by josephillips85** [comment] 2019-09-17 07:16
Users with the issue before:
1.Patch the PI with the new code and reboot it (is necesary a reboot after the patch) 6008af88ac82ef6ed98114921ff42077724b1309

2.Delete the Key from registry
\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\usbflags\1D6B01040100
3.Restart Computer


Please feedback about this.

![image](https://user-images.githubusercontent.com/28776122/65019585-215d6e80-d8f1-11e9-93bc-5ad45e18c0b3.png)

**Comment by clouser123** [comment] 2019-09-18 03:26
> Patch the PI with the new code and reboot it 

Since I'm new to this, I presume simply running the install command won't cut it, right? What command should I use to correctly patch it?

**Comment by josephillips85** [comment] 2019-09-18 03:30
No
The patch is in the commit pending for confirmation after that you can
install the patch  directly from the installer

You should patch hidgamepad.py from the commit I do before.

**Comment by josephillips85** [comment] 2019-09-18 07:26
@clouser123 
to update the hidgamepad.py you can perform this following procedure on a already installed PI

sudo systemctl stop gamepademu
sudo curl https://raw.githubusercontent.com/josephillips85/gamepademu/v1.1/Core/hidgamepad.py > /opt/gamepademu/hidgamepad.py
sudo reboot

and follow the instructions from 2 to 3

> > Patch the PI with the new code and reboot it
> 
> Since I'm new to this, I presume simply running the install command won't cut it, right? What command should I use to correctly patch it?

**Comment by clouser123** [comment] 2019-09-18 18:11
That's great. I will have a look as soon as I can. 

What do you mean by
> and follow the instructions from 2 to 3
?

I'm afraid I don't know how to patch the PI with the new code as you mentioned above even after looking around. Perhaps it was something I went over without noticing.

**Comment by josephillips85** [comment] 2019-09-18 18:44
MeAns that after that follow the step 2 and 3 from the instructions

**Comment by DaSu15** [comment] 2019-09-18 18:45
Will installing everything from the scratch have the updated version?

**Comment by josephillips85** [comment] 2019-09-18 18:55
Nope

This commit is pending for testing and I’m waiting your confirmation

After everything is tested I will add to master branch so the install from
the scratch will have the patched version

**Comment by DaSu15** [comment] 2019-09-18 18:56
When I try to patch it, it says permission denied. What could be possibly wrong?

**Comment by DaSu15** [comment] 2019-09-18 18:58
![image](https://user-images.githubusercontent.com/54862271/65177448-5f78a080-da5f-11e9-9e8c-e5f3d958457f.png)

**Comment by josephillips85** [comment] 2019-09-18 19:00
@dasu15 
where you get the error?
your screenshot  don't show any error.

**Comment by DaSu15** [comment] 2019-09-18 19:02
![image](https://user-images.githubusercontent.com/54862271/65177746-00675b80-da60-11e9-91c5-923c5534a20f.png)
My bad. Here's a proper screenshot

**Comment by josephillips85** [comment] 2019-09-18 19:04
Try
sudo su
Before run the script

**Comment by DaSu15** [comment] 2019-09-18 19:26
The buttons work now.
There are quite a few other issues tho.
1. The latency is quite big. Definitely a lot worse than on normal controllers
2. You can't move around the pause menu after picking a song in Clone Hero (I assume this being caused by the tilt axis)
3. I had a weird bug, where it would register every button I press, but there was over a second delay between each input was shown. So after sending a lot of inputs, the guitar was playing by itself for solid 20 seconds.

**Comment by josephillips85** [comment] 2019-09-18 20:01
hi @DaSu15 
glad to hear

1.Try unplug the power for the pi and plug again Let me know if the  latency issues gone
2.Pause menu Use strum Up or down for move
3.Probably caused by the latency issue.

**Comment by josephillips85** [comment] 2019-09-18 20:02
@DaSu15 Latency issue happend on gamepad test on windows?

**Comment by DaSu15** [comment] 2019-09-18 20:35
I can't see the controller in my devices and therefore I tested it in Clone Hero. 

After restarting the pi, I couldn't get the issue to as bad state as it was for the first time, but it was still significantly worse than normal guitars.

I have 2 builds of the game and the issue with the pause menu not working only occured on one of them (and couple of other issues that I noticed afterwards). Not quite sure why, but the game just kinda breaks for some reason.

The whammy and tilt is set as buttons and not axises, and I couldn't really get tilt to work in game.

I think removing the tilt completely might fix some of the issues, since it's constantly pressing "the button"

**Comment by josephillips85** [comment] 2019-09-18 20:48
@DaSu15 
The guitar itself send tilt information  via Axis and a button(is the normal behaivor of the guitar) so im passing both to the gamepad if you run the gamepad test when you perform tilt up press a button , and when you perform tilt down press another button . 

Whammy is a axis (the guitar send this information) 

The latency is a ms issue? 
happend on the gamepad test on windows?

Thanks.

**Comment by DaSu15** [comment] 2019-09-18 20:59
As I said the guitar doesn't show up in the device manage at all for some reason, so I'm not able to test it on Windows. But I don't think that there should be any difference. 

Also another thing I noticed that the latency seems a little bit inconsistent. Which could mean that the latency might be caused by the guitar or the pi.

**Comment by josephillips85** [comment] 2019-09-19 07:21
@DaSu15 im trying to replicate the issue of latency on my side but looks everything fine here ... well im not a goood Guitar hero player too.. lol so maybe playing on medium works great but for play on expert maybe can be a issue 

just for understand. 
`def process(ba_rawmessage):
    rawmessage = bytes(ba_rawmessage)
    keys = rawmessage[0]
    strum_hexdata = rawmessage[4]
    buttons = rawmessage[1]
    tilt_hexdata = rawmessage[5]
    tilt_axis = rawmessage[19]
    whammybar_axis = rawmessage[6]`

if you see im processing the following things
keys=1 to 6 white and black keys
strum_hexdata = if you use the strum up or down or keep in the resting position
buttons = Pause ,Hero Power GHTV and Center Button Also Merged with tilt_hexdata thats mean when you perform the tilt up or down will going to press 2 different buttons
tilt_axis = tilt information received by the guitar
whammybar_axis = whammy bar axis information by the guitar.

so my question is tilt_axis necesary for the game?

**Comment by DaSu15** [comment] 2019-09-19 10:50
https://youtu.be/JHI0q72lPas, here's a video of the guitar doing its own thing.

You can definitely play easy songs without much issue with this latency (excluding the fact that it randomly starts working very poorly), but with anything harder it's not quite a viable option.

The tilt seems to work fine now. I just had to calibrate it in game.

I really think the issue might be in the bluetooth connection itself. I don't know if perhaps disabling wi-fi on the pi and some other stuff could make it any better?

**Comment by DaSu15** [comment] 2019-09-19 10:59
Also the latency seems to be very bad for some time every time you connect the guitar.

**Comment by josephillips85** [comment] 2019-09-19 23:07
@dasu15 
Two questions good player btw lol
1.i see the first 125 keys on your video plays well is this the desired behavior?

2.are you powering the pi with a external power supply or just with the USB port itself?

3.what os are you using ?

**Comment by DaSu15** [comment] 2019-09-20 17:20
1. The first 125 keys were somewhat playable, but still worse than normal guitars. 
2. I'm powering the pi with the USB port
3. Windows 10

**Closed as completed** 2019-09-22 19:44 UTC
Labels: bug

**Comment by josephillips85** [comment] 2019-09-22 19:46
Hi @DaSu15 
i check the issue of Windows and i set as close
Also i perform some changes to mitigate the High CPU uage that is causing latency.
Please Perform a clean install just to make sure everything is fine

In case the latency issue or random pressed keys continue open a new issue.

Thanks
